name: Integration & Unit test

on:
  pull_request:
    branches:
      - MOODLE_*_STABLE

jobs:
  PHPUnit:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          # Moodle 4.4
          - php: 8.1
            os: ubuntu-latest
            moodle: MOODLE_404_STABLE
            experimental: false
            dbtype: mysqli
            dependencies: |
              praxisdigital/local_pxsdk@master
          - php: 8.2
            os: ubuntu-latest
            moodle: MOODLE_404_STABLE
            dbtype: mysqli
            experimental: false
            dependencies: |
              praxisdigital/local_pxsdk@master
          - php: 8.3
            os: ubuntu-latest
            moodle: MOODLE_404_STABLE
            dbtype: mysqli
            experimental: false
            dependencies: |
              praxisdigital/local_pxsdk@master
          # MSSQL
          - php: 8.1
            os: ubuntu-latest
            moodle: MOODLE_404_STABLE
            experimental: false
            dbtype: sqlsrv
            dependencies: |
              praxisdigital/local_pxsdk@master
          - php: 8.2
            os: ubuntu-latest
            moodle: MOODLE_404_STABLE
            dbtype: sqlsrv
            experimental: false
            dependencies: |
              praxisdigital/local_pxsdk@master
          - php: 8.3
            os: ubuntu-latest
            moodle: MOODLE_404_STABLE
            dbtype: sqlsrv
            experimental: false
            dependencies: |
              praxisdigital/local_pxsdk@master

          # Moodle 5.0
          - php: 8.2
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: mysqli
            experimental: true
            dependencies: |
              praxisdigital/local_pxsdk@master
          - php: 8.3
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: mysqli
            experimental: true
            dependencies: |
              praxisdigital/local_pxsdk@master
          - php: 8.4
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: mysqli
            experimental: true
            dependencies: |
              praxisdigital/local_pxsdk@master
          # MSSQL
          - php: 8.2
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: sqlsrv
            experimental: true
            dependencies: |
              praxisdigital/local_pxsdk@master
          - php: 8.3
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: sqlsrv
            experimental: true
            dependencies: |
              praxisdigital/local_pxsdk@master
          - php: 8.4
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: mysqli
            experimental: true
            dependencies: |
              praxisdigital/local_pxsdk@master

    steps:
      - name: Unit testing & integration testing
        uses: praxisdigital/moodle-test-action@master
        with:
          plugin: format_pxgrid
          plugin-path: course/format/pxgrid
          os: ${{ matrix.os }}
          php: ${{ matrix.php }}
          dbtype: ${{ matrix.dbtype }}
          moodle: ${{ matrix.moodle }}
          experimental: ${{ matrix.experimental }}
          dependencies: ${{ matrix.dependencies }}
          PRIVATE_REPO_TOKEN: ${{ secrets.MOODLE_GH_KEY }}